# Generated by Django 3.0.5 on 2020-04-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieItem',
            new_name='BingeItem',
        ),
        migrations.DeleteModel(
            name='TVShowItem',
        ),
    ]
